echo "[tpp-script]====SET VARIABLES"

if [ -z "${CONNECT_CONFIG_STORAGE_TOPIC}" ]; then
  export CONNECT_CONFIG_STORAGE_TOPIC=${CONNECT_GROUP_ID}_connect-configs
fi

if [ -z "${CONNECT_OFFSET_STORAGE_TOPIC}" ]; then
  export CONNECT_OFFSET_STORAGE_TOPIC=${CONNECT_GROUP_ID}_connect-offsets
fi

if [ -z "${CONNECT_STATUS_STORAGE_TOPIC}" ]; then
  export CONNECT_STATUS_STORAGE_TOPIC=${CONNECT_GROUP_ID}_connect-status
fi

if [ -z "${CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR}" ]; then
  export CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=$REPLICATION_FACTOR
fi

if [ -z "${CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR}" ]; then
  export CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=$REPLICATION_FACTOR
fi

if [ -z "${CONNECT_STATUS_STORAGE_REPLICATION_FACTOR}" ]; then
  export CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=$REPLICATION_FACTOR
fi

if [ -z "${CONNECT_CONSUMER_SECURITY_PROTOCOL}" ]; then
  export CONNECT_CONSUMER_SECURITY_PROTOCOL=$CONNECT_SECURITY_PROTOCOL
fi

if [ -z "${CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION}" ]; then
  export CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION=$CONNECT_SSL_TRUSTSTORE_LOCATION
fi

if [ -z "${CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD}" ]; then
  export CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD=$CONNECT_SSL_TRUSTSTORE_PASSWORD
fi

if [ -z "${CONNECT_PRODUCER_SECURITY_PROTOCOL}" ]; then
  export CONNECT_PRODUCER_SECURITY_PROTOCOL=$CONNECT_SECURITY_PROTOCOL
fi

if [ -z "${CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION}" ]; then
  export CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=$CONNECT_SSL_TRUSTSTORE_LOCATION
fi

if [ -z "${CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD}" ]; then
  export CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=$CONNECT_SSL_TRUSTSTORE_PASSWORD
fi

if [ -z "${KAFKA_OPTS}" ]; then
  export KAFKA_OPTS=$JAVA_OPTS
fi

printenv

echo "[tpp-script]=====FINISH SET VARIABLES"