spring:
  application:
    name: kafka-batch-bottleneck-refactoring

server:
  port: 8080

auth-service:
  base-url: http://localhost:8081

kafka:
  bootstrapServers: localhost:9092
  consumer:
    topic: testTopic
    max-poll-records: 10


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  #file:
  #  name: app/out/app.log
  level:
    org.springframework.web: INFO
    ru.typik: DEBUG
    #reactor.kafka: DEBUG

