services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wait
    ports:
      - "5432:5432"
    volumes:
      - ../connector/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka-connect:
    image: wait-kafka-connector:latest
    depends_on:
      - kafka
      - postgres
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9093"
      CONNECT_GROUP_ID: "waitGroup"


