plugins {
    id "java"
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "17"
    }
}

def pluginsDir = file("$projectDir/plugins")
def extractedDir = file("$buildDir/extracted-plugins/plugins")
def dockerContextDir = layout.buildDirectory.dir("docker")
def dockerImageName = "wait-kafka-connector:latest"

tasks.register("unzipPlugins", Copy) {
    from {
        fileTree(pluginsDir).matching { include "*.zip" }.collect { zipTree(it) }
    }
    into extractedDir
}
tasks.register("copyJarToPlugins", Copy) {
    dependsOn(tasks.jar)

    from(tasks.jar.archiveFile)
    into("$buildDir/extracted-plugins/plugins/typik-plugin")
}

tasks.register("dockerPrepare") {
    dependsOn("unzipPlugins")
    dependsOn("copyJarToPlugins")
}

tasks.register("prepareDockerContext", Sync) {
    dependsOn("unzipPlugins")
    dependsOn("copyJarToPlugins")

    into(dockerContextDir)

    from("Dockerfile")
    from("app/scripts") {
        into("scripts")
    }
    from("app/tasks") {
        into("tasks")
    }
    from(extractedDir) {
        into("plugins")
    }
}

tasks.register("docker", Exec) {
    group = "docker"
    description = "Builds the connector Docker image"
    dependsOn("prepareDockerContext")

    workingDir(dockerContextDir.get().asFile)
    commandLine("docker", "build", "-t", dockerImageName, ".")
}

tasks.register("dockerTag") {
    group = "docker"
    description = "Prints the connector Docker image tag"
    doLast {
        println(dockerImageName)
    }
}

dependencies {
    implementation("org.apache.kafka:connect-api:3.8.0")
    implementation("org.apache.kafka:connect-json:3.8.0")
    implementation("org.slf4j:slf4j-api:2.0.17")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.17.0")
}
